services:
  darthvader:
    build: dnsserver
    hostname: darthvader
    networks:
      rededns:
          ipv4_address: 192.168.20.10
    volumes:
      - ./dnsserver/conf/primario/named.conf.options:/etc/bind/named.conf.options
      - ./dnsserver/conf/primario/named.conf.local:/etc/bind/named.conf.local
      - ./dnsserver/conf/primario/db.starwars.lan:/var/cache/bind/db.starwars.lan
      - ./dnsserver/conf/primario/db.20.168.192:/var/cache/bind/db.20.168.192
      - ./dnsserver/conf/primario/db.galaxia.lan:/var/cache/bind/db.galaxia.lan

  darthsidious:
    build: dnsserver
    hostname: darthsidious
    networks:
      rededns:
          ipv4_address: 192.168.20.11
    volumes:
      - ./dnsserver/conf/secundario/named.conf.options:/etc/bind/named.conf.options
      - ./dnsserver/conf/secundario/named.conf.local:/etc/bind/named.conf.local

  leia:
    build: dnsserver
    hostname: leia
    networks:
      rededns:
          ipv4_address: 192.168.20.106
    volumes:
      - ./dnsserver/conf/delegado/named.conf.options:/etc/bind/named.conf.options
      - ./dnsserver/conf/delegado/named.conf.local:/etc/bind/named.conf.local
      - ./dnsserver/conf/delegado/db.imperio.starwars.lan:/var/cache/bind/db.imperio.starwars.lan
      - ./dnsserver/conf/delegado/db.20.168.192:/var/cache/bind/db.20.168.192

  eq1:
    build: dnsserver
    hostname: eq1
    dns:
      - 192.168.20.10
      - 192.168.20.11
    networks:
      rededns:
          ipv4_address: 192.168.20.100
    volumes:
      - ./dnsclient/nsupdate/actualiza.txt:/actualiza.txt
      - ./dnsclient/nsupdate/update.key:/update.key
      - ./dnsclient/bind/rndc.conf:/etc/bind/rndc.conf
    
networks:
  rededns:
    ipam:
      config:
        - subnet: 192.168.20.0/24

