services:
  darthvader:
    build: dnsserver
    hostname: darthvader
    networks:
      rededns:
          ipv4_address: 192.168.20.10
    volumes:
      - ./dnsserver/conf/named.conf.options:/etc/bind/named.conf.options
      - ./dnsserver/conf/named.conf.local:/etc/bind/named.conf.local
      - ./dnsserver/conf/db.starwars.lan:/var/cache/bind/db.starwars.lan
      - ./dnsserver/conf/db.20.168.192:/var/cache/bind/db.20.168.192
  eq1:
    build: debian
    hostname: eq1
    dns:
      - 192.168.20.10
    networks:
      rededns:
          ipv4_address: 192.168.20.100
networks:
  rededns:
    ipam:
      config:
        - subnet: 192.168.20.0/24

